service: localstack-websockets

provider:
  name: aws
  deploymentBucket:
    name: localstack-websockets-serverless

package:
  exclude:
    - .venv/**

plugins:
  - serverless-deployment-bucket
  - serverless-localstack

custom:
  localstack:
    stages: [local]

functions:
  connectionHandler:
    handler: connect.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  defaultHandler:
    handler: default.handler
    events:
      - websocket:
          route: $default
  actionOneHandler:
    handler: handler-one.handler
    events:
      - websocket:
          route: test-action-one
  actionTwoHandler:
    handler: handler-two.handler
    events:
      - websocket:
          route: test-action-two
